"""Destructive FiftyOne operator for safe AlbumentationsX run cleanup."""

from __future__ import annotations

import logging
from collections.abc import Mapping
from os import PathLike
from typing import Any

import fiftyone.operators as foo
import fiftyone.operators.types as types
from fiftyone.operators.operator import RiskLevel

from albumentationsx_plugin.core import JSONDict
from albumentationsx_plugin.hosts.fiftyone.branding import ALBUMENTATIONS_ICON
from albumentationsx_plugin.hosts.fiftyone.cleanup_preview import build_cleanup_preview
from albumentationsx_plugin.hosts.fiftyone.forms.sections import add_collapsible_section
from albumentationsx_plugin.hosts.fiftyone.run_cleanup import CLEANUP_STATUS_OK, CLEANUP_STATUS_PARTIAL, cleanup_run
from albumentationsx_plugin.hosts.fiftyone.run_summary import list_deletable_run_keys

OPERATOR_NAME = "delete_albumentationsx_run"
OPERATOR_LABEL = "Delete AlbumentationsX Run"
RUN_KEY_FIELD_NAME = "run_key"
CONFIRM_FIELD_NAME = "confirm_delete"
STORAGE_ROOT_PARAM_NAME = "_storage_root"
_LOGGER = logging.getLogger(__name__)


class DeleteAlbumentationsXRun(foo.Operator):
    """FiftyOne App operator that deletes generated run outputs after confirmation."""

    @property
    def config(self) -> foo.OperatorConfig:
        return foo.OperatorConfig(
            name=OPERATOR_NAME,
            label=OPERATOR_LABEL,
            icon=ALBUMENTATIONS_ICON,
            description="Delete samples and files generated by an AlbumentationsX run.",
            dynamic=True,
            unlisted=True,
            allow_immediate_execution=True,
            allow_delegated_execution=False,
            allow_distributed_execution=False,
            risk_level=RiskLevel.HIGH,
        )

    # pyrefly: ignore[bad-override]
    def resolve_input(self, ctx: Any):
        params = _ctx_params(ctx)
        storage_root = _storage_root(params)
        dataset = getattr(ctx, "dataset", None)
        run_keys = list_deletable_run_keys(dataset, storage_root=storage_root) if dataset is not None else ()

        inputs = types.Object()
        selected_run = _selected_run_key(params.get(RUN_KEY_FIELD_NAME), run_keys)
        from_history = params.get("_history_run") is True
        # Never silently replace the run selected in history with another run.
        if from_history:
            selected_run = str(params.get(RUN_KEY_FIELD_NAME) or "")
            run_keys = (selected_run,) if selected_run in run_keys else ()
        if from_history and run_keys:
            inputs.str(RUN_KEY_FIELD_NAME, default=selected_run, view=types.HiddenView())
        elif run_keys:
            choices = types.AutocompleteView(label="Run key", allow_user_input=False)
            for run_key in run_keys:
                choices.add_choice(run_key, label=run_key)
            inputs.enum(
                RUN_KEY_FIELD_NAME,
                run_keys,
                label="Run key",
                default=selected_run,
                required=True,
                view=choices,
            )
        else:
            inputs.str(
                RUN_KEY_FIELD_NAME,
                label="Run key",
                description="No deletable AlbumentationsX runs were found for this dataset.",
            )
        if run_keys:
            try:
                preview = build_cleanup_preview(dataset, selected_run, storage_root=storage_root)
            except Exception as error:
                inputs.view(
                    "_cleanup_preview_error",
                    types.Warning(label="Cleanup preview unavailable", description=str(error)),
                    invalid=True,
                    error_message="Review or repair this run before deleting its outputs.",
                )
            else:
                inputs.view(
                    "_cleanup_preview",
                    types.Warning(
                        label=f"Delete outputs from {preview.run_label}",
                        description=(
                            f"Created: {preview.created_at or 'unknown'}. "
                            f"Delete {preview.sample_count} generated sample(s) and {preview.file_count} file(s). "
                            f"Already missing: {preview.missing_sample_count} sample(s), {preview.missing_file_count} file(s). "
                            f"File scope: {preview.run_dir}. The custom run is removed after successful cleanup. "
                            "Source samples and files are preserved; the manifest remains as a cleaned audit record."
                        ),
                    ),
                )
                details = types.Object()
                details.str(
                    "paths",
                    default="\n".join(preview.output_paths),
                    label="Manifest-listed relative paths",
                    view=types.CodeView(read_only=True),
                )
                add_collapsible_section(inputs, "_cleanup_files", "Files in this run", details)
                confirm_name = f"_confirm_run_{selected_run}" if from_history else CONFIRM_FIELD_NAME
                inputs.bool(
                    confirm_name,
                    label="Confirm deletion",
                    default=False,
                    required=True,
                    description="Delete generated samples and manifest-listed files shown above.",
                    view=types.CheckboxView(),
                    invalid=params.get(confirm_name) is not True,
                    error_message="Confirm the displayed deletion scope to continue."
                    if params.get(confirm_name) is not True
                    else "",
                )
        else:
            inputs.properties[RUN_KEY_FIELD_NAME].invalid = True
            inputs.properties[
                RUN_KEY_FIELD_NAME
            ].error_message = "This run has no deletable outputs. Return to Run history."
        if from_history:
            inputs.btn(
                "_back_to_history",
                label="Back to Run history",
                prompt=True,
                on_click="@albumentations/albumentationsx/view_albumentationsx_run",
                params={
                    "run_key": selected_run,
                    **({STORAGE_ROOT_PARAM_NAME: str(storage_root)} if storage_root else {}),
                },
            )

        return types.Property(
            inputs,
            view=types.PromptView(
                label="AlbumentationsX · Delete generated outputs",
                submit_button_label="Delete generated outputs",
                cancel_button_label="Cancel",
            ),
        )

    # pyrefly: ignore[bad-override]
    def resolve_output(self, ctx: Any):
        outputs = types.Object()
        outputs.str("run_key", label="Run key")
        outputs.str("status", label="Status")
        outputs.str("message", label="Message")
        outputs.str("manifest_path", label="Manifest path")
        outputs.str("fiftyone_run_key", label="FiftyOne run key")
        outputs.int("deleted_sample_count", label="Deleted samples")
        outputs.int("skipped_sample_count", label="Skipped samples")
        outputs.int("deleted_file_count", label="Deleted files")
        outputs.int("skipped_file_count", label="Skipped files")
        outputs.int("failed_file_count", label="Failed files")
        outputs.bool("custom_run_deleted", label="Custom run deleted")
        outputs.bool("custom_run_missing", label="Custom run missing")
        outputs.bool("confirmed", label="Confirmed")
        outputs.str("errors_json", label="Errors")
        params = _ctx_params(ctx)
        outputs.btn(
            "_back_to_history",
            label="Back to Run history",
            prompt=True,
            on_click="@albumentations/albumentationsx/view_albumentationsx_run",
            params={key: params[key] for key in (RUN_KEY_FIELD_NAME, STORAGE_ROOT_PARAM_NAME) if key in params},
        )
        return types.Property(outputs)

    # pyrefly: ignore[bad-override]
    def resolve_placement(self, ctx: Any):
        return None

    def execute(self, ctx: Any) -> JSONDict:
        params = _ctx_params(ctx)
        run_key = _selected_run_key(params.get(RUN_KEY_FIELD_NAME), ())
        confirmed = _confirmed(params.get(CONFIRM_FIELD_NAME))
        if params.get("_history_run") is True:
            # UI confirmations are bound to the selected run; legacy API callers
            # retain their existing explicit confirm_delete contract.
            confirmed = params.get(f"_confirm_run_{run_key}") is True
            if confirmed:
                build_cleanup_preview(ctx.dataset, run_key, storage_root=_storage_root(params))
        result = cleanup_run(
            ctx.dataset,
            run_key,
            confirmed=confirmed,
            storage_root=_storage_root(params),
        )
        _trigger_dataset_reload(ctx, result)
        return result.to_dict()


def _ctx_params(ctx: Any | None) -> Mapping[str, object]:
    params = getattr(ctx, "params", {}) if ctx is not None else {}
    return params if isinstance(params, Mapping) else {}


def _selected_run_key(raw_value: object, run_keys: tuple[str, ...]) -> str:
    if isinstance(raw_value, str) and raw_value.strip():
        value = raw_value.strip()
        if not run_keys or value in run_keys:
            return value
    return run_keys[0] if run_keys else ""


def _confirmed(raw_value: object) -> bool:
    return raw_value is True


def _trigger_dataset_reload(ctx: Any, result: Any) -> None:
    if getattr(result, "status", "") not in {CLEANUP_STATUS_OK, CLEANUP_STATUS_PARTIAL}:
        return

    trigger = getattr(ctx, "trigger", None)
    if not callable(trigger):
        return
    try:
        trigger("reload_dataset")
    except Exception:
        _LOGGER.debug("Error while triggering FiftyOne dataset reload", exc_info=True)
        return


def _storage_root(params: Mapping[str, object]) -> str | PathLike[str] | None:
    value = params.get(STORAGE_ROOT_PARAM_NAME)
    if isinstance(value, str):
        return value
    return value if isinstance(value, PathLike) else None
