"""Destructive FiftyOne operator for safe AlbumentationsX run cleanup."""

from __future__ import annotations

from collections.abc import Mapping
from os import PathLike
from typing import Any

import fiftyone.operators as foo
import fiftyone.operators.types as types
from fiftyone.operators.operator import RiskLevel

from albumentationsx_plugin.core import JSONDict
from albumentationsx_plugin.hosts.fiftyone.run_cleanup import cleanup_run
from albumentationsx_plugin.hosts.fiftyone.run_summary import list_available_run_keys

OPERATOR_NAME = "delete_albumentationsx_run"
OPERATOR_LABEL = "Delete AlbumentationsX Run"
RUN_KEY_FIELD_NAME = "run_key"
CONFIRM_FIELD_NAME = "confirm_delete"
STORAGE_ROOT_PARAM_NAME = "_storage_root"


class DeleteAlbumentationsXRun(foo.Operator):
    """FiftyOne App operator that deletes generated run outputs after confirmation."""

    @property
    def config(self) -> foo.OperatorConfig:
        return foo.OperatorConfig(
            name=OPERATOR_NAME,
            label=OPERATOR_LABEL,
            description="Delete samples and files generated by an AlbumentationsX run.",
            dynamic=True,
            allow_immediate_execution=True,
            allow_delegated_execution=False,
            allow_distributed_execution=False,
            risk_level=RiskLevel.HIGH,
        )

    # pyrefly: ignore[bad-override]
    def resolve_input(self, ctx: Any):
        params = _ctx_params(ctx)
        storage_root = _storage_root(params)
        dataset = getattr(ctx, "dataset", None)
        run_keys = list_available_run_keys(dataset, storage_root=storage_root) if dataset is not None else ()

        inputs = types.Object()
        if run_keys:
            choices = types.AutocompleteView(label="Run key", allow_user_input=False)
            for run_key in run_keys:
                choices.add_choice(run_key, label=run_key)
            inputs.enum(
                RUN_KEY_FIELD_NAME,
                run_keys,
                label="Run key",
                default=_selected_run_key(params.get(RUN_KEY_FIELD_NAME), run_keys),
                required=True,
                view=choices,
            )
        else:
            inputs.str(
                RUN_KEY_FIELD_NAME,
                label="Run key",
                description="No persisted AlbumentationsX runs were found for this dataset.",
            )
        inputs.bool(
            CONFIRM_FIELD_NAME,
            label="Confirm deletion",
            default=False,
            required=True,
            description="Delete generated samples, manifest-listed output files, and the FiftyOne custom run.",
        )

        return types.Property(
            inputs,
            view=types.View(label=OPERATOR_LABEL),
        )

    # pyrefly: ignore[bad-override]
    def resolve_output(self, ctx: Any):
        outputs = types.Object()
        outputs.str("run_key", label="Run key")
        outputs.str("status", label="Status")
        outputs.str("message", label="Message")
        outputs.str("manifest_path", label="Manifest path")
        outputs.str("fiftyone_run_key", label="FiftyOne run key")
        outputs.int("deleted_sample_count", label="Deleted samples")
        outputs.int("skipped_sample_count", label="Skipped samples")
        outputs.int("deleted_file_count", label="Deleted files")
        outputs.int("skipped_file_count", label="Skipped files")
        outputs.int("failed_file_count", label="Failed files")
        outputs.bool("custom_run_deleted", label="Custom run deleted")
        outputs.bool("custom_run_missing", label="Custom run missing")
        outputs.bool("confirmed", label="Confirmed")
        outputs.str("errors_json", label="Errors")
        return types.Property(outputs)

    # pyrefly: ignore[bad-override]
    def resolve_placement(self, ctx: Any):
        return types.Placement(
            types.Places.SAMPLES_GRID_ACTIONS,
            types.Button(label=OPERATOR_LABEL),
        )

    def execute(self, ctx: Any) -> JSONDict:
        params = _ctx_params(ctx)
        result = cleanup_run(
            ctx.dataset,
            _selected_run_key(params.get(RUN_KEY_FIELD_NAME), ()),
            confirmed=_confirmed(params.get(CONFIRM_FIELD_NAME)),
            storage_root=_storage_root(params),
        )
        return result.to_dict()


def _ctx_params(ctx: Any | None) -> Mapping[str, object]:
    params = getattr(ctx, "params", {}) if ctx is not None else {}
    return params if isinstance(params, Mapping) else {}


def _selected_run_key(raw_value: object, run_keys: tuple[str, ...]) -> str:
    if isinstance(raw_value, str) and raw_value.strip():
        return raw_value
    return run_keys[0] if run_keys else ""


def _confirmed(raw_value: object) -> bool:
    return raw_value is True


def _storage_root(params: Mapping[str, object]) -> str | PathLike[str] | None:
    value = params.get(STORAGE_ROOT_PARAM_NAME)
    if isinstance(value, str):
        return value
    return value if isinstance(value, PathLike) else None
