"""FiftyOne annotation conversion helpers for augmentation execution."""

from albumentationsx_plugin.hosts.fiftyone.annotations.assets import (
    MaterializedAnnotationAssets,
    materialize_annotation_assets,
)
from albumentationsx_plugin.hosts.fiftyone.annotations.conversion import (
    AnnotationTargets,
    annotation_payload_from_sample,
    labels_from_annotation_payload,
    target_data_from_annotation_payload,
    transformed_annotation_payload,
)
from albumentationsx_plugin.hosts.fiftyone.annotations.fields import (
    ANNOTATION_EXCLUDED_FIELDS_KEY,
    ANNOTATION_FIELD_PARAM_PREFIX,
    ANNOTATION_PAYLOAD_KEY,
    SELECTED_LABEL_FIELDS_PARAM_NAME,
    AnnotationField,
    AnnotationFieldSelection,
    annotation_field_param_name,
    annotation_field_selection_is_explicit,
    annotation_pipeline_compatibility_conflicts,
    annotation_pipeline_field_roles,
    annotation_run_metadata,
    annotation_target_requirements_from_inputs,
    list_supported_annotation_fields,
    resolve_annotation_field_selection,
    resolve_annotation_fields,
    safe_list_supported_annotation_fields,
    selected_annotation_fields_from_params,
    target_and_copy_fields,
    validate_annotation_pipeline_compatibility,
    validate_selected_annotation_fields,
)

__all__ = [
    "ANNOTATION_EXCLUDED_FIELDS_KEY",
    "ANNOTATION_FIELD_PARAM_PREFIX",
    "ANNOTATION_PAYLOAD_KEY",
    "SELECTED_LABEL_FIELDS_PARAM_NAME",
    "AnnotationField",
    "AnnotationFieldSelection",
    "AnnotationTargets",
    "MaterializedAnnotationAssets",
    "annotation_field_param_name",
    "annotation_field_selection_is_explicit",
    "annotation_pipeline_compatibility_conflicts",
    "annotation_pipeline_field_roles",
    "annotation_run_metadata",
    "annotation_target_requirements_from_inputs",
    "materialize_annotation_assets",
    "annotation_payload_from_sample",
    "labels_from_annotation_payload",
    "list_supported_annotation_fields",
    "resolve_annotation_field_selection",
    "resolve_annotation_fields",
    "safe_list_supported_annotation_fields",
    "selected_annotation_fields_from_params",
    "target_and_copy_fields",
    "target_data_from_annotation_payload",
    "transformed_annotation_payload",
    "validate_annotation_pipeline_compatibility",
    "validate_selected_annotation_fields",
]
