"""Host-neutral contracts for the AlbumentationsX plugin."""

from albumentationsx_plugin.core.errors import (
    ErrorCode,
    HostAdapterError,
    InvalidParameterError,
    MediaIOError,
    PluginError,
    UnsupportedTransformError,
)
from albumentationsx_plugin.core.interfaces import (
    HostSampleAdapter,
    OutputStorageBackend,
    ParameterSchemaProvider,
    PipelineFactory,
    PipelineRunner,
    RunStore,
    TransformCatalogProvider,
)
from albumentationsx_plugin.core.models import (
    DEFAULT_BRIGHTNESS_RANGE,
    DEFAULT_CONTRAST_RANGE,
    DEFAULT_CROP_SIZE,
    DEFAULT_TRANSFORM_PROBABILITY,
    FIXED_TRANSFORM_NAMES,
    MAX_OUTPUTS_PER_SAMPLE,
    AugmentationInput,
    AugmentationResult,
    CapabilityStatus,
    FieldKind,
    FormFieldSchema,
    JSONDict,
    JSONValue,
    PipelineConfig,
    RunManifest,
    TransformCapability,
    TransformConfig,
)

__all__ = [
    "AugmentationInput",
    "AugmentationResult",
    "CapabilityStatus",
    "DEFAULT_BRIGHTNESS_RANGE",
    "DEFAULT_CONTRAST_RANGE",
    "DEFAULT_CROP_SIZE",
    "DEFAULT_TRANSFORM_PROBABILITY",
    "ErrorCode",
    "FieldKind",
    "FIXED_TRANSFORM_NAMES",
    "FormFieldSchema",
    "HostSampleAdapter",
    "HostAdapterError",
    "InvalidParameterError",
    "JSONDict",
    "JSONValue",
    "MediaIOError",
    "MAX_OUTPUTS_PER_SAMPLE",
    "OutputStorageBackend",
    "ParameterSchemaProvider",
    "PipelineConfig",
    "PipelineFactory",
    "PipelineRunner",
    "PluginError",
    "RunManifest",
    "RunStore",
    "TransformCapability",
    "TransformCatalogProvider",
    "TransformConfig",
    "UnsupportedTransformError",
]
